### ISSUE TITLE
Eventual Conectivity for Login, SignUp and Info screens

### ISSUE THREAD

**Issue by jf-garciam1** [ISIS3510-202410-Team5/Android-Kotlin#55]
Needs to be resolved the eventual conectivity for internet for the Login Screens and the info Screens, the checking of the connectivity should be on demand.

**Comment by msgalvan1207** [comment]
development branch was added after the pull request was merged. Should close manually

**Comment by jf-garciam1** [comment]
Finished the eventual connectivity on the 3 views
